this brings most of the tests into a passable state.
caught a lot of col_names vs colnames and a issue with the 2dBackground where its being handed the numpy array back to the functon which didnt expect the numpy array but the 2Dbackground object first.

at the moment the only test which fail are the following:
test_ast -> test_run_basic, test_run_harsh_inputs
test_matching -> TestBandMatch -> test_order_catalogue_jwst_col_names, test_order_catalogue_filter_meta, test_order_catalogue_filter_col_names. test_match.

to get most of the tests to run, i had to add a hardcoded filterString to most of the function calls. And had to clean up runs mode to access the correct files and clean up after itself.

Theres still random files appearing in the test folder. which i need to chase down. as well as those failing tests.

those tests cover errors of the following:
ValueError: All elements of input 'data' must be finite.

assert [<Table length=0>\n F115W \nfloat64\n-------, <Table length=0>\n F770W \nfloat64\n-------, <Table length=0>\n F187N \nfloat64\n-------] == [<Table length=0>\n F115W \nfloat64\n-------, <Table length=0>\n F187N \nfloat64\n-------, <Table length=0>\n F770W \nfloat64\n-------]
E
E         (pytest_assertion plugin: representation of details failed: /home/alanstokes/starbug2/star_bug_env/lib/python3.12/site-packages/_pytest/assertion/util.py:380: ValueError: The truth value of an empty array is ambiguous. Use `array.size > 0` to check that an array is not empty..
E          Probably an object has a faulty __repr__.)

ValueError: The truth value of an empty array is ambiguous. Use `array.size > 0` to check that an array is not empty.

TypeError: only dimensionless scalar quantities can be converted to Python scalars